name = "MyExample"
uuid = "0efd09a6-4858-4828-92d2-58d6f9660b65"
authors = ["Lyle Regenwetter"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
